# Generated by Django 4.2.7 on 2024-09-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_post_id_alter_postcomment_id_alter_profile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='base.tag'),
        ),
    ]
